# description
name: "mini-ssh"
version: "0.1.0"
slug: "ssh"
description: "minimal ssh access to home assistant"
codenotary: 9296944+orhid@users.noreply.github.com

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386


# behaviour
init: false # use s6
startup: services

hassio_api: true
hassio_role: manager
host_dbus: true

ports:
  22/tcp: 22
ports_description:
  22/tcp : ssh server port (empty to disable)
map:
  - ssl:rw
  - homeassistant_config:rw
  - addons:rw
  - all_addon_configs:rw
  - media:rw
  - share:rw

# options
options:
  authorized_keys: []
  apks: []
schema:
  authorized_keys:
    - str
  apks:
    - str

# ingress
ingress: true
panel_icon: mdi:console
panel_title: terminal
